In [1]:
import numpy as np

In [2]:
#生成一個等差數列，首數為0，尾數為20，公差為1的數列。
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
#step默認為1

In [4]:
#2.呈上題，將以上數列取出偶數。
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#3.呈1題，將數列取出3的倍數。
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [13]:
#5.請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a.ndim , '---陣列有多少維度') 
print(a.shape , '---每個維度的大小')
print(a.size , '---陣列當中有幾個元素')
print(a.dtype , '---陣列中的資料型態')
print(a.itemsize , '---陣列中每個元素佔用的空間')
print(a.data , '---陣列所存在的記憶體位置')

2 ---陣列有多少維度
(3, 5) ---每個維度的大小
15 ---陣列當中有幾個元素
int32 ---陣列中的資料型態
4 ---陣列中每個元素佔用的空間
<memory at 0x00000084CCBD6450> ---陣列所存在的記憶體位置


In [14]:
#4.[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
print('只會把第一層的元素轉換成 List，多層的話只有第一層會轉')
print('tolist() 才能達成多層的型態轉換')

只會把第一層的元素轉換成 List，多層的話只有第一層會轉
tolist() 才能達成多層的型態轉換


In [20]:
#6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.arange(1, 42, 2).reshape(3, 7)

print(list(a))
print(a.tolist())

[array([ 1,  3,  5,  7,  9, 11, 13]), array([15, 17, 19, 21, 23, 25, 27]), array([29, 31, 33, 35, 37, 39, 41])]
[[1, 3, 5, 7, 9, 11, 13], [15, 17, 19, 21, 23, 25, 27], [29, 31, 33, 35, 37, 39, 41]]
